### ISSUE TITLE
Login instruction

### ISSUE THREAD

**Issue by genmancoder** [kaarlosasiang/bankist-app#1]
Hi, I'd like to request a feature. I'm having problems signing in as a user.

**Comment by kaarlosasiang** [comment]
> Hi, I'd like to request a feature. I'm having problems signing in as a user.
Hi @genmancoder! You can try to sign in using these sample accounts -> username: "js", pin: '1111'  or  username: "jd", pin: "2222". 
Both accounts have different locales, meaning the format of dates and numbers will change for every user. Account with username "js" lives in UK and account with username "jd" lives in USA.

**Comment by genmancoder** [comment]
Thank you very much!
